import { IconType } from "react-icons";
import {
  MdCategory,
  MdShare,
  MdVideocam,
  MdEditNote,
  MdBugReport,
  MdSearch,
  MdTableRows,
  MdShoppingBag,
  MdCode,
  MdDesignServices,
  MdTranslate,
  MdPhotoCamera,
  MdHeadphones,
  MdSchool,
  MdAnalytics,
  MdPayments,
  MdManageAccounts,
  MdGppBad,
  MdBlock,
  MdShield,
  MdEditDocument,
  MdSupportAgent,
  MdHandshake,
  MdStorefront,
  MdToll,
  MdSavings,
  MdTimer,
  MdAccountBalanceWallet,
  MdCreditCard,
  MdPhoneAndroid,
  MdAccountBalance,
  MdPostAdd,
  MdVerified,
  MdGroup,
  MdRateReview,
  MdTaskAlt,
  MdAssignmentTurnedIn,
  MdPersonAdd,
  MdAddTask,
  MdSchedule,
  MdLanguage,
  MdVerifiedUser,
  MdHelp,
  MdGavel,
  MdPrivacyTip,
  MdQuiz,
  MdRocketLaunch,
  MdEngineering,
  MdBusinessCenter,
  MdTrendingUp,
  MdBolt,
  MdPublic,
  MdStorage,
  MdSettingsSuggest,
  MdLock,
  MdCookie,
  MdHowToReg,
  MdHistory,
  MdChildCare,
  MdUpdate,
  MdVisibilityOff,
  MdFilterList,
  MdSwapHoriz,
  MdShoppingCart,
  MdInfo,
  MdStar,
  MdContactSupport,
  MdOpenInNew,
  MdPerson,
  MdArrowForward,
  MdCheckCircle,
} from "react-icons/md";

const iconMap: Record<string, IconType> = {
  // categories
  category: MdCategory,
  share: MdShare,
  videocam: MdVideocam,
  edit_note: MdEditNote,
  bug_report: MdBugReport,
  search: MdSearch,
  table_rows: MdTableRows,
  shopping_bag: MdShoppingBag,
  code: MdCode,
  design_services: MdDesignServices,
  translate: MdTranslate,
  photo_camera: MdPhotoCamera,
  headphones: MdHeadphones,
  school: MdSchool,
  analytics: MdAnalytics,
  // payments / coins
  payments: MdPayments,
  toll: MdToll,
  savings: MdSavings,
  timer: MdTimer,
  account_balance_wallet: MdAccountBalanceWallet,
  credit_card: MdCreditCard,
  phone_android: MdPhoneAndroid,
  account_balance: MdAccountBalance,
  shopping_cart: MdShoppingCart,
  swap_horiz: MdSwapHoriz,
  // tasks / work
  post_add: MdPostAdd,
  rate_review: MdRateReview,
  task_alt: MdTaskAlt,
  assignment_turned_in: MdAssignmentTurnedIn,
  add_task: MdAddTask,
  // users
  group: MdGroup,
  person_add: MdPersonAdd,
  manage_accounts: MdManageAccounts,
  person_check: MdHowToReg,
  person: MdPerson,
  // legal / privacy
  gpp_bad: MdGppBad,
  block: MdBlock,
  shield: MdShield,
  edit_document: MdEditDocument,
  support_agent: MdSupportAgent,
  handshake: MdHandshake,
  storefront: MdStorefront,
  gavel: MdGavel,
  privacy_tip: MdPrivacyTip,
  visibility_off: MdVisibilityOff,
  lock: MdLock,
  cookie: MdCookie,
  child_care: MdChildCare,
  update: MdUpdate,
  history: MdHistory,
  database: MdStorage,
  settings_suggest: MdSettingsSuggest,
  // misc
  schedule: MdSchedule,
  language: MdLanguage,
  verified_user: MdVerifiedUser,
  verified: MdVerified,
  help: MdHelp,
  quiz: MdQuiz,
  rocket_launch: MdRocketLaunch,
  engineering: MdEngineering,
  business_center: MdBusinessCenter,
  trending_up: MdTrendingUp,
  bolt: MdBolt,
  public: MdPublic,
  filter_list: MdFilterList,
  info: MdInfo,
  star: MdStar,
  contact_support: MdContactSupport,
  open_in_new: MdOpenInNew,
  arrow_forward: MdArrowForward,
  check_circle: MdCheckCircle,
};

export default iconMap;
